// SPDX-License-Identifier: GPL-3.0-only
//
// GENERATED by apps/desktop-bridge/build/driverVectors.mjs. Do not edit.
//
// The devices this driver publishes, generated from the bridge's own device
// specs. The driver needs each model's name, manufacturer and port names, and
// the bridge addresses the driver's entities by the spec's port index — so the
// two halves are only correct while they agree, and generating one from the
// other makes them the same list rather than two lists that must be kept in
// step by hand.
//
// The order is the device index carried on the wire.
#pragma once

#include <CoreFoundation/CoreFoundation.h>
#include <cstddef>

namespace vrmc_devices {

// launchpad-x
static const CFStringRef kPorts0[] = {
    CFSTR("LPX DAW"),
    CFSTR("LPX MIDI"),
};

// launchpad-pro-mk3
static const CFStringRef kPorts1[] = {
    CFSTR("LPProMK3 MIDI"),
    CFSTR("LPProMK3 DIN"),
    CFSTR("LPProMK3 DAW"),
};

struct DeviceSpec {
  const char *model;
  CFStringRef name;
  CFStringRef manufacturer;
  const CFStringRef *portNames;
  size_t portCount;
};

inline const DeviceSpec kDevices[] = {
    {"launchpad-x", CFSTR("Launchpad X"), CFSTR("Focusrite - Novation"), kPorts0, 2},
    {"launchpad-pro-mk3", CFSTR("Launchpad Pro MK3"), CFSTR("Focusrite - Novation"), kPorts1, 3},
};

inline constexpr size_t kDeviceCount = sizeof(kDevices) / sizeof(kDevices[0]);

/// Ports on the widest device, for fixed-size per-port arrays.
inline constexpr size_t kMaxPortsPerDevice = 3;

}  // namespace vrmc_devices
